### ISSUE TITLE
Strip "hdfs://" from path

### ISSUE THREAD

**Issue by gglanzani** [dask/hdfs3#169]
Hi all,

I was thinking about opening a PR to ensure we strip `hdfs://` from the `path` (both in the file system and file objects).

For the file system object, the best place would be to put it in `ensure_bytes`, while it could be in the `__init__` of the file object.

Would anyone object to such an approach?

The rationale is that we often do

```python
path = 'hdfs://something'
df.write.format('parquet').save(path)
# do more here
hdfs = hdfs3.HDFileSystem()
hdfs.ls(path)  # or other methods
```
and we currently need to strip `path` otherwise `hdfs3` will fail to find the path.

What do you think? (Again, I volunteer to do the work, add tests, etc.)

**Comment by martindurant** [comment]
Firstly, I should say that hdfs3 is no longer unedrgoing much development, as pyarrow's hdfs implementation is now a mature replacement. You may find, that if you use that implementation, this issue is already solved for you.

On the specifics, `ensure_bytes` would not be a good place to put this code, since it is not only called with path strings. Instead, you would end up doing something like all of the `if path.startswith('s3://')` for the s3fs case or its [generalization](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py#L75).

If you would still like to take this on, I would be happy to review it.

**Comment by gglanzani** [comment]
Hi Martin

I didn't know about the new pyarrow situation. I guess I'll have to embrace the JNI way of doing things :)

I'll close the issue, I haven't done any work on it yet. We might always reopen.
