### ISSUE TITLE
Update hdfs3 and libhdfs3 packages on Anaconda.org

### ISSUE THREAD

**Issue by frol** [dask/hdfs3#75]
https://anaconda.org/search?q=hdfs3

As you can see, dask channel contains outdated packages (1 minor version behind, yet it shouldn't be outdated at all!) and anaconda channel has hdfs3 package only for Python 2.7.

**Comment by koverholt** [comment]
Thanks for reminding us about this, @frol.

I've integrated `hdfs3` with the anaconda.org builders so that we can update the conda packages on the `dask` channel more easily.

I've uploaded conda packages for the latest version of `hdfs3` (0.1.1) for Python 2.7, 3.4, and 3.5 on linux-64, which can be installed via

```
conda install hdfs3 -c dask
```

The process of building the `libhdfs3` has a more complex toolchain, but the library has not changed since the last time we built conda packages.

@mrocklin and @martindurant, anaconda.org will build packages on each commit. After a release, you can move the resulting built conda packages from the `dev` label to the `main` label to make conda packages available on https://anaconda.org/dask/hdfs3/files. I can also help with this if you ping me during a release.
